[package]
name = "libresample"
description = "Wrapper for libresample (resampling library for sounds)"
license = "BSD"
version = "0.1.0"
authors = ["Gleb Pomykalov <gleb@pomykalov.ru>"]

[dependencies]
libc = "0.2.17"

